program: experimentWB.py
project: segtree
method: random
metric: 
  name: valid_dataset_iou
  goal: maximize
parameters:
  network:
    values: ["fpn", "unet", "unetplusplus", "deeplabv3","deeplabv3plus"]
  encoder:
    values: ["resnet18","resnet34","resnet50","densenet121","densenet169","efficientnet-b0","efficientnet-b1","efficientnet-b2","efficientnet-b3","efficientnet-b4","efficientnet-b5","efficientnet-b6","efficientnet-b7","mobilenetv2","timm-mobilenetv3_large_100","vgg11","vgg13"]
command:
  - python
  - ${program}
  - ${args}